# Forge Configuration
# See https://github.com/JacobDoucet/forge for documentation

forgeVersion: 1.0.3

specDir: ./models

go:
  outDir: ./generated/go
  pkgRoot: github.com/JacobDoucet/forge/example/generated/go

typescript:
  outDir: ./generated/typescript

kotlin:
  outDir: ./generated/kotlin
  pkgRoot: com.forge.example.generated
