# Forge Configuration
# See https://github.com/JacobDoucet/forge for documentation

forgeVersion: v1.0.3

specDir: ./models

go:
  outDir: ./apps/backend/generated
  pkgRoot: github.com/JacobDoucet/forge/example/apps/backend/generated

typescript:
  outDir: ./apps/frontend/src/generated

kotlin:
  outDir: ./apps/kotlin/generated
  pkgRoot: com.forge.example.generated
