version: "3"

vars:
  BINARY_NAME: forge
  VERSION:
    sh: git describe --tags --always --dirty 2>/dev/null || echo "dev"
  COMMIT:
    sh: git rev-parse --short HEAD 2>/dev/null || echo "none"
  BUILD_DATE:
    sh: date -u +"%Y-%m-%dT%H:%M:%SZ"
  LDFLAGS: -s -w -X github.com/JacobDoucet/forge/cmd.Version={{.VERSION}} -X github.com/JacobDoucet/forge/cmd.Commit={{.COMMIT}} -X github.com/JacobDoucet/forge/cmd.BuildDate={{.BUILD_DATE}}

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the forge binary
    cmds:
      - go build -ldflags "{{.LDFLAGS}}" -o {{.BINARY_NAME}} .
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_NAME}}"

  install:
    desc: Install forge to $GOPATH/bin
    cmds:
      - go install -ldflags "{{.LDFLAGS}}" .

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format all Go files
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  # Example module tasks
  example:build:
    desc: Build and generate the example module (Go, TypeScript, Kotlin)
    dir: example
    cmds:
      - ../{{.BINARY_NAME}} build
    deps:
      - build

  example:verify:
    desc: Verify the example generated code compiles
    dir: example
    cmds:
      - go build ./generated/go/...
    deps:
      - example:build

  # Development workflow
  dev:
    desc: Build forge and regenerate example (full dev cycle)
    cmds:
      - task: build
      - task: example:build
      - task: example:verify

  clean:
    desc: Remove all build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -rf example/generated

  # Release helpers
  release:check:
    desc: Run all checks before release
    cmds:
      - task: fmt
      - task: tidy
      - task: lint
      - task: test
      - task: example:verify

  release:tag:
    desc: Create a new version tag (usage task release:tag -- v1.0.0)
    cmds:
      - cmd: 'sh -c ''if [ -z "{{.CLI_ARGS}}" ]; then echo "Usage: task release:tag -- v1.0.0"; exit 1; fi'''
      - git tag -a {{.CLI_ARGS}} -m "Release {{.CLI_ARGS}}"
      - echo "Created tag {{.CLI_ARGS}}"
      - echo "Run 'git push origin {{.CLI_ARGS}}' to publish"

  release:
    desc: Full release workflow (usage task release -- v1.0.0)
    cmds:
      - task: release:check
      - cmd: 'sh -c ''if [ -z "{{.CLI_ARGS}}" ]; then echo "Usage task release -- v1.0.0"; exit 1; fi'''
      - git tag -a {{.CLI_ARGS}} -m "Release {{.CLI_ARGS}}"
      - echo "Created tag {{.CLI_ARGS}}. Run 'git push origin {{.CLI_ARGS}}' to publish"
